### ISSUE TITLE
Why use customized base64 URL encoding?

### ISSUE THREAD

**Issue by huangjj27** [tencentyun/tls-sig-api-v2-python#1]
Python's `base64` lib provides `base64.b64encode(msg, altchars)` for url safe encoding. I notice that the customized encoding is also used in [other versions of this API](https://github.com/tencentyun/tls-sig-api-v2-java/blob/master/src/main/java/com/tencentyun/Base64URL.java), and am curious about why not using the provided encoding method?

**Comment by weijunyi** [comment]
没有什么特殊的理由，就是沿用了之前的一分部代码，如果您这边有更好的方式可以直接提 PR。

**Comment by huangjj27** [comment]
No PR anymore. Here is [my confidential usable version](https://github.com/huangjj27/TLSSigAPI)
