### ISSUE TITLE
`json.dump(m)` produces a string with spaces, while other implements don't output spaces

### ISSUE THREAD

**Issue by huangjj27** [tencentyun/tls-sig-api-v2-python#2]
For example, [c# implement](https://github.com/tencentyun/tls-sig-api-v2-cs/blob/master/tls-sig-api-v2-cs/TLSSigAPIv2.cs#L85) directly concat a **no-space string**. I think the python version should use the same implement!

**Comment by weijunyi** [comment]
是的，json.dumps 的参数加上 separators=(',',':')，能够消除序列化后含有空格的问题。不过这个问题不影响使用，而且对生成出来的 token 长度影响不大，所以近期应该不会去处理。

再次感谢反馈。
